### PR TITLE
fix: update dependencies

### LINKED ISSUE #29: CI is failing because of updated `unist` types
Due to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54413, CI is now failing with

```sh
Error: [typecheck] src/index.ts(90,14): error TS2339: Property 'title' does not exist on type 'Literal<unknown, Data> & Parent<Node<Data>, Data>'.
Error: [typecheck] src/index.ts(92,26): error TS2339: Property 'value' does not exist on type 'Node<Data>'.
Error: [typecheck] src/index.ts(92,41): error TS2339: Property 'url' does not exist on type 'Literal<unknown, Data> & Parent<Node<Data>, Data>'.
Error: [typecheck] src/index.ts(97,14): error TS2339: Property 'url' does not exist on type 'Literal<unknown, Data> & Parent<Node<Data>, Data>'.
Error: [typecheck] src/index.ts(163,32): error TS2339: Property 'tagName' does not exist on type 'Parent<Node<Data>, Data>'.
Error: [typecheck] src/index.ts(164,38): error TS2339: Property 'properties' does not exist on type 'Parent<Node<Data>, Data>'.
```

@wooorm Can you point me into the right direction of fixing this please?
I don't have a clue tbh. 🤔

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Fixes #29

---

CC/ @wooorm

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
@wooorm really weird that `@types/mdast` is working locally, but not in CI 🤔

```sh
Error: [typecheck] src/index.ts(90,14): error TS2339: Property 'title' does not exist on type 'Literal & Parent'.
Error: [typecheck] src/index.ts(92,26): error TS2339: Property 'value' does not exist on type 'Content'.
[typecheck]   Property 'value' does not exist on type 'Paragraph'.
Error: [typecheck] src/index.ts(92,41): error TS2339: Property 'url' does not exist on type 'Literal & Parent'.
Error: [typecheck] src/index.ts(97,14): error TS2339: Property 'url' does not exist on type 'Literal & Parent'.
Error: [typecheck] src/index.ts(163,32): error TS2339: Property 'tagName' does not exist on type 'Parent'.
Error: [typecheck] src/index.ts(164,38): error TS2339: Property 'properties' does not exist on type 'Parent'.
```

**Comment by wooorm** [comment]
a) I meant using `@types/mdast` *instead* of `@types/unist`. To use specific nodes, like `Link` for links
b) maybe `rm -rf node_modules` locally and reinstalling will surface the problems

**Comment by JounQin** [comment]
Maybe you should clear cache on CI first.

**Review by kentcdodds — APPROVED** [review]
👍

**Comment by kentcdodds** [comment]
Whoops, sometimes I approve before reading the comments or looking at CI 🤦‍♂️

> Maybe you should clear cache on locally/CI first.

Unfortunately GitHub actions don't have a way to clear the cache 😬

File: src/index.ts [hunk 1]
```diff
@@ -82,19 +82,19 @@ const remarkEmbedder: Plugin<[RemarkEmbedderOptions]> = ({
...
 
       const {children} = paragraphNode
-      const node = children[0] as Literal & Parent
+      const node = children[0] as Link | Text
       const isText = node.type === 'text'
       // it's a valid link if there's no title, and the value is the same as the URL
       const isValidLink =
         node.type === 'link' &&
-        node.title === null &&
+        node.title === undefined &&
```
Comment (MichaelDeBoey) [inline src/index.ts:90]: According to `@types/mdast`, `title` is of type `string | undefined` and not `null`

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f2b0b6ec0095de2c52b9799bb3260ee17f79182b/types/mdast/index.d.ts#L201-L204

Comment (MichaelDeBoey) [reply src/index.ts:90]: @wooorm this seems not to be correct according to our tests 🤔

File: src/index.ts [hunk 2]
```diff
@@ -82,19 +82,19 @@ const remarkEmbedder: Plugin<[RemarkEmbedderOptions]> = ({
       }
 
       const {children} = paragraphNode
-      const node = children[0] as Literal & Parent
+      const node = children[0] as Link | Text
```
Comment (wooorm) [inline src/index.ts:85]: Why the `|`? It’s just a `Link`, presumably, right?

File: src/index.ts (hunk 1 above)
Comment (wooorm) [reply src/index.ts:90]: You could use both. Some tools use one or the other

Comment (MichaelDeBoey) [reply src/index.ts:90]: So types need to be changed then? 🤔

As using `undefined` is breaking our tests now

Comment (kentcdodds) [reply src/index.ts:90]: Could just change it to `node.title == null`.

File: src/index.ts (hunk 2 above)
Comment (MichaelDeBoey) [reply src/index.ts:85]: L86 is checking if it's a `Text`
```ts
const isText = node.type === 'text'
```

We return early if it's not `Text` **or** if it's an invalid link.
But that seems weird as a node can't be both text & valid link 🤔

@kentcdodds can probably give some more context about this check

File: src/index.ts (hunk 1 above)
Comment (wooorm) [reply src/index.ts:90]: I’d use `!node.title` as the comment above this conditions read “no title”.

`null` has been historically used everywhere (by me). TypeScript folks seem to not like `null`, hence type definitions only uses `undefined` 🤷‍♂️ We had some discussions about it if I remember correctly. I’m slowly moving towards `undefined`, but IMO most code should check for both in most cases.

Comment (MichaelDeBoey) [reply src/index.ts:90]: Will change to double equals instead of triple equals

Will also create a PR to update the types, to make them correct.

File: src/index.ts (hunk 2 above)
Comment (kentcdodds) [reply src/index.ts:85]: Yeah, we only *want* to find `link`s but we could find just about anything as the first and only child to a paragraph. But now that I think about it, if `isValidLink` is true, then `isText` will always be false so we could probably remove the `isText` completely.

Comment (wooorm) [reply src/index.ts:85]: Alternatively, there are a bunch of utilities to narrow these types: https://github.com/ChristianMurphy/unifiedjs.github.io/blob/docs/typescript-guide-and-recipes/doc/learn/node-type-narrowing-in-typescript.md.
You can do this type safe!

Comment (MichaelDeBoey) [reply src/index.ts:85]: > But now that I think about it, if `isValidLink` is true, then `isText` will always be false so we could probably remove the `isText` completely.

@kentcdodds We should keep the `isText` check as we're also transforming text that's not a valid link apparently 🤔

**Review by kentcdodds — APPROVED** [review]
LGTM 👍

**Comment by kentcdodds** [comment]
Hmm... Looks like we've got some test failures.

**Comment by MichaelDeBoey** [comment]
@kentcdodds Tests are failing because we should keep the `isText` check as we're also transforming text that's not a valid link apparently 🤔 (see https://github.com/remark-embedder/core/runs/3079154136#step:6:36)

**Comment by kentcdodds** [comment]
Oh right, that's actually the most common use case 😅 https://astexplorer.net/#/gist/e15b6dea43f639b57bfeeb894a4a44bd/d01873eee84788877d955ad972c20500cbd2a630

Good thing we have tests for that!

**Comment by MichaelDeBoey** [comment]
@kentcdodds caching problem is still there, but locally all is green
Schermafbeelding 2021-07-16 om 15 56 54

**Comment by kentcdodds** [comment]
Let's see what happens if I just merge

**Comment by MichaelDeBoey** [comment]
@kentcdodds Seems like there's still something wrong 😕
https://github.com/remark-embedder/core/runs/3087181241

**Comment by kentcdodds** [comment]
I'm actually experiencing errors on a fresh clone:

```
~/Desktop 🦍
$ git clone https://github.com/remark-embedder/core.git
Cloning into 'core'...
remote: Enumerating objects: 186, done.
remote: Counting objects: 100% (63/63), done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 186 (delta 30), reused 26 (delta 10), pack-reused 123
Receiving objects: 100% (186/186), 65.03 KiB | 924.00 KiB/s, done.
Resolving deltas: 100% (92/92), done.
~/Desktop 🦍
$ cd core 
~/Desktop/core (main) 🦍
$ npm run setup
running command with prefix "setup"

> @remark-embedder/core@0.0.0-semantically-released setup
> npm install && npm run validate -s

npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated

added 1189 packages, and audited 1190 packages in 20s

165 packages are looking for funding
  run `npm fund` for details

12 vulnerabilities (6 moderate, 6 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
[build] Successfully compiled 1 file with Babel (645ms).
[build] Generating TypeScript definitions
[typecheck] src/index.ts(92,26): error TS2339: Property 'value' does not exist on type 'StaticPhrasingContent'.
[typecheck]   Property 'value' does not exist on type 'Emphasis'.
[typecheck] src/index.ts(97,19): error TS2339: Property 'value' does not exist on type 'Link'.
[typecheck] src/index.ts(163,32): error TS2339: Property 'tagName' does not exist on type 'Parent'.
[typecheck] src/index.ts(164,38): error TS2339: Property 'properties' does not exist on type 'Parent'.
[typecheck] npm run typecheck --silent exited with code 1
--> Sending SIGTERM to other processes..
[test] npm run test --silent -- --coverage exited with code SIGTERM
--> Sending SIGTERM to other processes..
[build] npm run build --silent exited with code SIGTERM
--> Sending SIGTERM to other processes..
[lint] npm run lint --silent exited with code SIGTERM
NPM command npm run setup -- failed with code 1
```
