### PR TITLE
fix: fix type-check

### LINKED ISSUE #32: CI is failing
> I'm actually experiencing errors on a fresh clone:
> 
> ```
> ~/Desktop 🦍
> $ git clone https://github.com/remark-embedder/core.git
> Cloning into 'core'...
> remote: Enumerating objects: 186, done.
> remote: Counting objects: 100% (63/63), done.
> remote: Compressing objects: 100% (48/48), done.
> remote: Total 186 (delta 30), reused 26 (delta 10), pack-reused 123
> Receiving objects: 100% (186/186), 65.03 KiB | 924.00 KiB/s, done.
> Resolving deltas: 100% (92/92), done.
> ~/Desktop 🦍
> $ cd core 
> ~/Desktop/core (main) 🦍
> $ npm run setup
> running command with prefix "setup"
> 
> > @remark-embedder/core@0.0.0-semantically-released setup
> > npm install && npm run validate -s
> 
> npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
> npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
> npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
> 
> added 1189 packages, and audited 1190 packages in 20s
> 
> 165 packages are looking for funding
>   run `npm fund` for details
> 
> 12 vulnerabilities (6 moderate, 6 high)
> 
> To address issues that do not require attention, run:
>   npm audit fix
> 
> To address all issues (including breaking changes), run:
>   npm audit fix --force
> 
> Run `npm audit` for details.
> [build] Successfully compiled 1 file with Babel (645ms).
> [build] Generating TypeScript definitions
> [typecheck] src/index.ts(92,26): error TS2339: Property 'value' does not exist on type 'StaticPhrasingContent'.
> [typecheck]   Property 'value' does not exist on type 'Emphasis'.
> [typecheck] src/index.ts(97,19): error TS2339: Property 'value' does not exist on type 'Link'.
> [typecheck] src/index.ts(163,32): error TS2339: Property 'tagName' does not exist on type 'Parent'.
> [typecheck] src/index.ts(164,38): error TS2339: Property 'properties' does not exist on type 'Parent'.
> [typecheck] npm run typecheck --silent exited with code 1
> --> Sending SIGTERM to other processes..
> [test] npm run test --silent -- --coverage exited with code SIGTERM
> --> Sending SIGTERM to other processes..
> [build] npm run build --silent exited with code SIGTERM
> --> Sending SIGTERM to other processes..
> [lint] npm run lint --silent exited with code SIGTERM
> NPM command npm run setup -- failed with code 1
> ```

_Originally posted by @kentcdodds in https://github.com/remark-embedder/core/pull/30#issuecomment-881757529_

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Fixes #32

---

CC/ @wooorm

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -89,14 +90,13 @@ const remarkEmbedder: Plugin<[RemarkEmbedderOptions]> = ({
         node.type === 'link' &&
         !node.title &&
         node.children.length === 1 &&
-        node.children[0].value === node.url
-      if (!isText && !isValidLink) {
+        (node.children[0] as Text).value === node.url
```
Comment (MichaelDeBoey) [inline src/index.ts:93]: @wooorm
`Link`'s `children` are typed as `StaticPhrasingContent[]`, but I think they're actually `[Text]`, no?

**Review by kentcdodds — APPROVED** [review]
LGTM! And I checked CI before reviewing 😅

File: src/index.ts (hunk 1 above)
Comment (wooorm) [reply src/index.ts:93]: No, emphasis, images, inline code and such, all also can exist in links. Just not other links

Comment (MichaelDeBoey) [reply src/index.ts:93]: @wooorm how would they look like then when putting them in Markdown?

Comment (wooorm) [reply src/index.ts:93]:
```
[*emphasis*](https://example.com)
[**strong**](https://example.com)
[![image]()](https://example.com)
...
```

Comment (MichaelDeBoey) [reply src/index.ts:93]: As there's always only 1 child, the type should be `[StaticPhrasingContent]` instead of `StaticPhrasingContent[]`, no?

Comment (wooorm) [reply src/index.ts:93]: There is not always one type. Things can exist together in links: `[*emphasis* text **strong** text image ~delete~](https://example.com)`

Comment (MichaelDeBoey) [reply src/index.ts:93]: > As there's always only 1 child, the type should be [StaticPhrasingContent] instead of StaticPhrasingContent[], no?

`[**strong** text](https://example.com)` is a use-case of having multiple children, my bad 😅
